### ISSUE TITLE
Codificación

### ISSUE THREAD

**Issue by jalbertoroman** [codeforspain/ds-limites-administrativos#2]
Me acabo de dar cuenta, que los acentos y la ñ no salen bien. p. ej. Castilla y León 
En QGIS el shapefile no da problemas. Con otros shp del gobierno, en qgis se solucionaba cambiando el encoding a windows 1252. 

He probado añadiendo al script, -lco ENCODING=UTF-8, pero no va... creo que es un problema de ogr2ogr.  ¿alguna idea?

**Comment by inigoflores** [comment]
Prueba a invocar `ogr2ogr` así:

    ogr2ogr --config SHAPE_ENCODING "UTF-8" -f GeoJSON -t_srs crs:84 output.geojson input.shp

**Comment by jalbertoroman** [comment]
Gracias @inigoflores! Solucionado.
